# Generated by Django 2.1.7 on 2019-03-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='active',
            field=models.BooleanField(default=True, verbose_name='is_published'),
        ),
    ]
