# Generated by Django 2.1.7 on 2019-04-15 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190415_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
