# Generated by Django 2.1.7 on 2019-04-15 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190415_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='need_logged_user',
        ),
    ]
