# Generated by Django 2.1.7 on 2019-04-17 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190415_2153'),
        ('blog', '0002_auto_20190326_1539'),
    ]

    operations = [
    ]
