# Generated by Django 2.2.1 on 2019-06-06 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190507_1444'),
        ('blog', '0011_auto_20190604_2036'),
    ]

    operations = [
    ]
