# Generated by Django 2.2.1 on 2019-06-06 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_merge_20190606_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='survey',
        ),
        migrations.AlterUniqueTogether(
            name='response',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='response',
            name='survey',
        ),
        migrations.RemoveField(
            model_name='response',
            name='user',
        ),
        migrations.DeleteModel(
            name='Answers',
        ),
        migrations.DeleteModel(
            name='Questions',
        ),
        migrations.DeleteModel(
            name='Response',
        ),
        migrations.DeleteModel(
            name='Survey',
        ),
    ]
