# Generated by Django 2.2.1 on 2019-06-06 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='response',
            options={},
        ),
        migrations.RemoveField(
            model_name='answers',
            name='user',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='choices',
        ),
        migrations.AddField(
            model_name='questions',
            name='answers',
            field=models.ManyToManyField(related_name='answers', to='survey.Answers'),
        ),
        migrations.AddField(
            model_name='response',
            name='answer',
            field=models.ManyToManyField(related_name='responses', to='survey.Answers', verbose_name='Answer'),
        ),
        migrations.AddField(
            model_name='response',
            name='question',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='survey.Questions', verbose_name='Question'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answers',
            name='answer',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='answers',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='survey.Questions'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='questions',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Survey'),
        ),
        migrations.AlterField(
            model_name='response',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='response',
            unique_together=set(),
        ),
    ]
